### ISSUE TITLE
求大佬解答

### ISSUE THREAD

**Issue by hhhwnxsmn** [maomingyang1314/MACOS--AMD-3700X-TUFB450-ROG5700XT-#1]
可以问一下bios设置要改啥吗，我会跳这个，然后镜像是在哪里下的呀
![QQ图片20200921201448](https://user-images.githubusercontent.com/71644964/93765303-39c04180-fc47-11ea-817e-1f1bd6a89f83.jpg)

**Comment by maomingyang1314** [comment]
bios我玩太久忘记了，网上一搜一大把，efi我自己搞的。

**Comment by hhhwnxsmn** [comment]
华硕tuf系列的amd找不到啊，别的型号有的选项我直接找不到，能加QQ带带孩子嘛

**Comment by maomingyang1314** [comment]
很多选项我也是跟着B站视频来的，快速启动和安全启动都关闭，差不多就可以了，bios更改，网上有很多教程，黑果小兵大大的网页中有MacOS的镜像。

**Comment by w127520** [comment]
一样的主板U配置，显卡不一样 用你的EFI 卡在log:exitbs:start

**Comment by maomingyang1314** [comment]
哪张显卡

**Comment by maomingyang1314** [comment]
N卡是不支持的vega64这种好像需要补丁，我的5700xt是免驱动的。

**Comment by w127520** [comment]
RX

> N卡是不支持的vega64这种好像需要补丁，我的5700xt是免驱动的。

RX580

**Comment by hhhwnxsmn** [comment]
大佬，big sur安装的时候都正常(进系统显卡识别啥都正常，但是关机再启动的时候，加载完苹果标志就开始黑屏了，咋解决啊

**Comment by maomingyang1314** [comment]
使用的是最新的efi2么？你有注入三码么？你的引导区有没有复制到硬盘上。如果都做了的话，你显卡的cpu，主板是哪一张

**Comment by maomingyang1314** [comment]
> 大佬，big sur安装的时候都正常（但系统关机识别启动都当，但是关机再启动的时候，加载完苹果标志就开始黑屏了，咋解决啊

系统镜像在黑果小兵的部落阁有，我提供的efi都需要自己注入三码的。

**Comment by hhhwnxsmn** [comment]
是最新的efi2，注入了三码，也复制到了硬盘上。显卡是技嘉5700xtoc，8g。cpu3600，主板和你一样（之前15.7用的也是你的efi，是完美的呀

**Comment by maomingyang1314** [comment]
你是重装系统，还是从原来10.15.7升级上去的。开机的时候，刷新一下NVram试试。而且，更新新系统，是需要等很久的。你让他运行半小时试试

**Comment by hhhwnxsmn** [comment]
我是重装系统（nvram也刷新过。还是不行。还是说我显卡不行？

**Comment by maomingyang1314** [comment]
我觉得，既然你在装系统的时候是正常的，那么efi就没有问题，如果efi有问题，那你是无法装系统的

**Comment by hhhwnxsmn** [comment]
所以就不知道咋办了（悲。

**Comment by maomingyang1314** [comment]
所以，你不试试 重装一下系统么？

**Comment by hhhwnxsmn** [comment]
重装，只装黑果（各种法子都试过了，还是会再重启以后进不去，u盘都没拔也不行

**Comment by hhhwnxsmn** [comment]
https://www.bilibili.com/video/BV12a4y1p7we?from=search&seid=2336434673964688736（就是这个视频的那种黑屏，不过我的进不去

**Comment by hhhwnxsmn** [comment]
屏蔽串口，好了（哭
